#!/bin/bash

function cToF()
{
	temp=$(awk "BEGIN {printf \"%.2f\", 1.8 * $temp + 32}")
	echo $temp	
	return $temp
}

function currentTemp
{
	temp=$(awk "BEGIN {printf \"%.2f\", ((4*$1)+40)*0.25}")
	echo $temp
	return $temp	
}

function lengthInInches()
{
	local temp=$1*12
	temp=$(($temp+$2))
	return $temp
}

function triangleArea()
{
	temp=$(awk "BEGIN {printf \"%.2f\", ($1*$2)*0.5}")
	echo $temp
	return $temp
}

function sumCoins()
{
	local pennies=$4
	local temp=$(($3*5))
	pennies=$(($pennies+$temp))
	temp=$(($2*10))
	pennies=$(($pennies+$temp))
	temp=$(($1*25))
	pennies=$(($pennies+$temp))
	return $pennies
}

function circleArea()
{
	return $(awk "BEGIN {printf \"%.2f\", $1*$2}")
}

echo "Welcome to the Utility Script. Select a number for the calculation you want:"
echo "1) Celsius to Fahrenheit"
echo "2) Cricket Temperature"
echo "3) Length in Inches"
echo "4) Triangle Area"
echo "5) Coin Counter"
echo "6) Cylinder Volume"
echo
read responce

if [ $responce -gt 6 ]; then
	echo "Invalid entry try again."
	exit 1
else
	case $responce in
		1) echo -n "Enter the temperature in celcius: "
			read temp
			cToF $temp;;
		2) echo -n "Enter number of chirps heard in 15 seconds:"
			read chirps
			currentTemp $chirps;;
		3) echo -n "Enter number of feet: "
			read feet  
			echo -n "Enter number of inches: "
			read inch
			lengthInInches $feet $inch;;
		4) echo -n "Enter the length of triangle's base: "
			read base
			echo -n "and height: "
			read height
			triangleArea $base $height;;
		5) echo -n "Enter number of quarters: "
			read quarters
			echo -n "Enter number of dimes: "
			read dimes
			echo -n "Enter number of nickels: "
			read nickels 
			echo -n "Enter number of pennies: "
			read pennies
			sumCoins $quarters $dimes $nickels $pennies;;
		6) echo -n "Enter radius of the base: " 
			read base
			echo -n "Enter height: " 
			read height
			cylinderVolume $base $height
	#	*) echo "Not a valid entry. Bye.";;
	esac
fi

echo $?
