#! /bin/bash

if [ $# -ne 3 ]
then
	echo "Error - There needs to be 3 arguments"
	echo "Syntax: $0 number [+-*/] number"
	exit 1
fi

case $2 in 
	"+") echo `expr $1 + $3`;;
	"-") echo `expr $1 - $3`;;
	"*") echo `expr $1 \* $3`;;
	"/") echo `expr $1 \/ $3`;;
	*) echo "That is not a valid operation.";;
esac
